Gauss I

In [4]:
# Python3 code for Gauss's Forward Formula
# importing library
import numpy as np

# function for calculating coefficient of Y 
def p_cal(p, n): 

	temp = p 
	for i in range(1, n): 
		if(i%2==1):
			temp * (p - i)
		else:
			temp * (p + i)
	return temp 
# function for factorial
def fact(n): 
	f = 1
	for i in range(2, n + 1): 
		f *= i
	return f 

# storing available data
n = 7 
x = [ 1, 1.05, 1.10, 1.15, 1.20, 1.25, 1.30 ] 

y = [[0 for i in range(n)] 
		for j in range(n)] 
y[0][0] = 2.7183
y[1][0] = 2.8577 
y[2][0] = 3.0042
y[3][0] = 3.1582 
y[4][0] = 3.3201 
y[5][0] = 3.4903 
y[6][0] = 3.6693 

# Generating Gauss's triangle
for i in range(1, n): 
	for j in range(n - i): 
		y[j][i] = np.round((y[j + 1][i - 1] - y[j][i - 1]),4) 

# Printing the Triangle 
for i in range(n): 
	print(x[i], end = "\t") 
	for j in range(n - i): 
		print(y[i][j], end = "\t") 
	print("") 

# Value of Y need to predict on 
value = 1.17 

# implementing Formula
sum = y[int(n/2)][0] 
p = (value - x[int(n/2)]) / (x[1] - x[0])

for i in range(1,n): 
	print(y[int((n-i)/2)][i])
	sum = sum + (p_cal(p, i) * y[int((n-i)/2)][i]) / fact(i)

print("\nValue at", value, 
	"is", round(sum, 4)) 



1	2.7183	0.1394	0.0071	0.0004	0.0	0.0	0.0001	
1.05	2.8577	0.1465	0.0075	0.0004	0.0	0.0001	
1.1	3.0042	0.154	0.0079	0.0004	0.0001	
1.15	3.1582	0.1619	0.0083	0.0005	
1.2	3.3201	0.1702	0.0088	
1.25	3.4903	0.179	
1.3	3.6693	
0.1619
0.0079
0.0004
0.0
0.0001
0.0001

Value at 1.17 is 3.2246


Stirling

In [1]:
# Python3 program to demonstrate Stirling
# Approximation
import math

# Function to calculate value using 
# Stirling formula
def Stirling(x, fx, x1, n):

	y1 = 0 N1 = 1 d = 1
	N2 = 1 d2 = 1 
	temp1 = 1 temp2 = 1
	k = 1 l = 1 
	delta = [[0 for i in range(n)]
				for j in range(n)]

	h = x[1] - x[0]
	s = math.floor(n / 2)
	a = x[s]
	u = (x1 - a) / h

	# Preparing the forward difference
	# table
	for i in range(n - 1): 
		delta[i][0] = fx[i + 1] - fx[i]
	for i in range(1, n - 1):
		for j in range(n - i - 1):
			delta[j][i] = (delta[j + 1][i - 1] -
						delta[j][i - 1])

	# Calculating f(x) using the Stirling formula
	y1 = fx[s]

	for i in range(1, n):
		if (i % 2 != 0): 
			if (k != 2): 
				temp1 *= (pow(u, k) - pow((k - 1), 2))
			else:
				temp1 *= (pow(u, 2) - pow((k - 1), 2))
			k += 1
			d *= i
			s = math.floor((n - i) / 2)
			y1 += (temp1 / (2 * d)) * (delta[s][i - 1] +
									delta[s - 1][i - 1])
		else:
			temp2 *= (pow(u, 2) - pow((l - 1), 2))
			l += 1
			d *= i
			s = math.floor((n - i) / 2)
			y1 += (temp2 / (d)) * (delta[s][i - 1])

	print(round(y1, 3))

# Driver Code
n = 5
x = [0, 0.5, 1.0, 1.5, 2.0 ]
fx = [ 0, 0.191, 0.341, 0.433, 0.477]

# Value to calculate f(x)
x1 = 1.22
Stirling(x, fx, x1, n)

# This code is contributed by mits


0.389


In [4]:
import numpy as np

def calU(u, n):
    if n == 0:
        return 1
    result = u
    for i in range(1, n // 2 + 1):
        result *= (u - i)
    for i in range(1, n // 2):
        result *= (u + i)
    return result

def factorial(n):
    if n == 0 or n == 1:
        return 1
    return n * factorial(n - 1)

def bessels_interpolation(x, y, value):
    n = len(x)
    diff = np.zeros((n, n))
    diff[:, 0] = y
    
    for i in range(1, n):
        for j in range(n - i):
            diff[j, i] = diff[j + 1, i - 1] - diff[j, i - 1]
    
    if n % 2 == 1:
        index = n // 2
    else:
        index = n // 2 - 1
    
    u = (value - x[index]) / (x[1] - x[0])
    sum = (diff[2, 0] + diff[3, 0]) / 2
    
    for i in range(1, n):
        if i % 2 == 1:
            sum += ((u - 0.5) * calU(u, i - 1) * diff[index, i]) / factorial(i)
        else:
            index -= 1
            sum += (calU(u, i) * (diff[index, i] + diff[index + 1, i]) / (2 * factorial(i)))
    
    return sum

# Ví dụ sử dụng
x = np.array([25,26,27,28,29,30], dtype=float)
y = np.array([4, 3.846, 3.704, 3.571, 3.448, 3.333], dtype=float)  
x_o = 27.4

print("Value at", x_o, "found using Bessel's interpolation is", bessels_interpolation(x, y, x_o))

# Ví dụ sử dụng
x = np.array([25,26,27,28,29,30], dtype=float)
y = np.array([4, 3.846, 3.704, 3.571, 3.448, 3.333], dtype=float)  
x_o = 27.4


Value at 27.4 found using Bessel's interpolation is 3.6496783360000005


In [6]:
import numpy as np

def calU(u, n):
    if n == 0:
        return 1
    result = u
    for i in range(1, n // 2 + 1):
        result *= (u - i)
    for i in range(1, n // 2):
        result *= (u + i)
    return result

def factorial(n):
    if n == 0 or n == 1:
        return 1
    return n * factorial(n - 1)

def bessels_interpolation(x, y, value):
    n = len(x)
    diff = np.zeros((n, n))
    diff[:, 0] = y
    
    for i in range(1, n):
        for j in range(n - i):
            diff[j, i] = diff[j + 1, i - 1] - diff[j, i - 1]
    
    # In bảng sai phân
    print("Bảng sai phân:")
    print(diff)
    
    if n % 2 == 1:
        index = n // 2
    else:
        index = n // 2 - 1
    
    u = (value - x[index]) / (x[1] - x[0])
    sum = (diff[2, 0] + diff[3, 0]) / 2
    
    for i in range(1, n):
        if i % 2 == 1:
            sum += ((u - 0.5) * calU(u, i - 1) * diff[index, i]) / factorial(i)
        else:
            index -= 1
            sum += (calU(u, i) * (diff[index, i] + diff[index + 1, i]) / (2 * factorial(i)))
    
    return sum

# Ví dụ sử dụng
x = np.array([25, 26, 27, 28, 29, 30], dtype=float)
y = np.array([4, 3.846, 3.704, 3.571, 3.448, 3.333], dtype=float)  
x_o = 26.2

print("Value at", x_o, "found using Bessel's interpolation is", bessels_interpolation(x, y, x_o))

Bảng sai phân:
[[ 4.000e+00 -1.540e-01  1.200e-02 -3.000e-03  4.000e-03 -7.000e-03]
 [ 3.846e+00 -1.420e-01  9.000e-03  1.000e-03 -3.000e-03  0.000e+00]
 [ 3.704e+00 -1.330e-01  1.000e-02 -2.000e-03  0.000e+00  0.000e+00]
 [ 3.571e+00 -1.230e-01  8.000e-03  0.000e+00  0.000e+00  0.000e+00]
 [ 3.448e+00 -1.150e-01  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 3.333e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]]
Value at 26.2 found using Bessel's interpolation is 3.8168500480000005
